-- depends_on: {{ source('raw_tse', 'receitas') }}
-- Camada privada: linha_original conserva todas as colunas fonte antes dos casts.
with tipado as (
    select
        {{ data_br('dt_geracao') }} as dt_geracao,
        hh_geracao::varchar as hh_geracao,
        nullif({{ texto('aa_eleicao') }}, '-4')::varchar as aa_eleicao,
        nullif({{ texto('cd_tipo_eleicao') }}, '-4')::varchar as cd_tipo_eleicao,
        nm_tipo_eleicao::varchar as nm_tipo_eleicao,
        nullif({{ texto('cd_eleicao') }}, '-4')::varchar as cd_eleicao,
        ds_eleicao::varchar as ds_eleicao,
        {{ data_br('dt_eleicao') }} as dt_eleicao,
        st_turno::varchar as st_turno,
        tp_prestacao_contas::varchar as tp_prestacao_contas,
        {{ data_br('dt_prestacao_contas') }} as dt_prestacao_contas,
        nullif({{ texto('sq_prestador_contas') }}, '-4')::varchar as sq_prestador_contas,
        sg_uf::varchar as sg_uf,
        sg_ue::varchar as sg_ue,
        nm_ue::varchar as nm_ue,
        {{ documento_fonte("nullif(trim(nr_cnpj_prestador_conta), '-4')") }}
            as nr_cnpj_prestador_conta,
        nullif({{ texto('cd_cargo') }}, '-4')::varchar as cd_cargo,
        ds_cargo::varchar as ds_cargo,
        nullif({{ texto('sq_candidato') }}, '-4')::varchar as sq_candidato,
        nullif({{ texto('nr_candidato') }}, '-4')::varchar as nr_candidato,
        nm_candidato::varchar as nm_candidato,
        {{ documento_fonte("nullif(trim(nr_cpf_candidato), '-4')") }} as nr_cpf_candidato,
        {{ documento_fonte("nullif(trim(nr_cpf_vice_candidato), '-4')") }} as nr_cpf_vice_candidato,
        nullif({{ texto('nr_partido') }}, '-4')::varchar as nr_partido,
        sg_partido::varchar as sg_partido,
        nm_partido::varchar as nm_partido,
        nullif({{ texto('cd_fonte_receita') }}, '-4')::varchar as cd_fonte_receita,
        ds_fonte_receita::varchar as ds_fonte_receita,
        nullif({{ texto('cd_origem_receita') }}, '-4')::varchar as cd_origem_receita,
        ds_origem_receita::varchar as ds_origem_receita,
        nullif({{ texto('cd_natureza_receita') }}, '-4')::varchar as cd_natureza_receita,
        ds_natureza_receita::varchar as ds_natureza_receita,
        nullif({{ texto('cd_especie_receita') }}, '-4')::varchar as cd_especie_receita,
        ds_especie_receita::varchar as ds_especie_receita,
        nullif({{ texto('cd_cnae_doador') }}, '-4')::varchar as cd_cnae_doador,
        ds_cnae_doador::varchar as ds_cnae_doador,
        {{ documento_fonte("nullif(trim(nr_cpf_cnpj_doador), '-4')") }} as nr_cpf_cnpj_doador,
        nm_doador::varchar as nm_doador,
        nm_doador_rfb::varchar as nm_doador_rfb,
        nullif({{ texto('cd_esfera_partidaria_doador') }}, '-4')::varchar
            as cd_esfera_partidaria_doador,
        ds_esfera_partidaria_doador::varchar as ds_esfera_partidaria_doador,
        sg_uf_doador::varchar as sg_uf_doador,
        nullif({{ texto('cd_municipio_doador') }}, '-4')::varchar as cd_municipio_doador,
        nm_municipio_doador::varchar as nm_municipio_doador,
        nullif({{ texto('sq_candidato_doador') }}, '-4')::varchar as sq_candidato_doador,
        nullif({{ texto('nr_candidato_doador') }}, '-4')::varchar as nr_candidato_doador,
        nullif({{ texto('cd_cargo_candidato_doador') }}, '-4')::varchar
            as cd_cargo_candidato_doador,
        ds_cargo_candidato_doador::varchar as ds_cargo_candidato_doador,
        nullif({{ texto('nr_partido_doador') }}, '-4')::varchar as nr_partido_doador,
        sg_partido_doador::varchar as sg_partido_doador,
        nm_partido_doador::varchar as nm_partido_doador,
        nullif({{ texto('nr_recibo_doacao') }}, '-4')::varchar as nr_recibo_doacao,
        nullif({{ texto('nr_documento_doacao') }}, '-4')::varchar as nr_documento_doacao,
        nullif({{ texto('sq_receita') }}, '-4')::varchar as sq_receita,
        {{ data_br('dt_receita') }} as dt_receita,
        ds_receita::varchar as ds_receita,
        {{ numero_br('vr_receita') }} as vr_receita,
        ds_natureza_recurso_estimavel::varchar as ds_natureza_recurso_estimavel,
        ds_genero::varchar as ds_genero,
        ds_cor_raca::varchar as ds_cor_raca,
        _coleta_id,
        _competencia,
        _competencia_data,
        _linha,
        _arquivo_original,
        _carregado_em,
        ano_arquivo,
        versao_id,
        layout_id,
        to_json(struct_pack(
            dt_geracao := dt_geracao,
            hh_geracao := hh_geracao,
            aa_eleicao := aa_eleicao,
            cd_tipo_eleicao := cd_tipo_eleicao,
            nm_tipo_eleicao := nm_tipo_eleicao,
            cd_eleicao := cd_eleicao,
            ds_eleicao := ds_eleicao,
            dt_eleicao := dt_eleicao,
            st_turno := st_turno,
            tp_prestacao_contas := tp_prestacao_contas,
            dt_prestacao_contas := dt_prestacao_contas,
            sq_prestador_contas := sq_prestador_contas,
            sg_uf := sg_uf,
            sg_ue := sg_ue,
            nm_ue := nm_ue,
            nr_cnpj_prestador_conta := nr_cnpj_prestador_conta,
            cd_cargo := cd_cargo,
            ds_cargo := ds_cargo,
            sq_candidato := sq_candidato,
            nr_candidato := nr_candidato,
            nm_candidato := nm_candidato,
            nr_cpf_candidato := nr_cpf_candidato,
            nr_cpf_vice_candidato := nr_cpf_vice_candidato,
            nr_partido := nr_partido,
            sg_partido := sg_partido,
            nm_partido := nm_partido,
            cd_fonte_receita := cd_fonte_receita,
            ds_fonte_receita := ds_fonte_receita,
            cd_origem_receita := cd_origem_receita,
            ds_origem_receita := ds_origem_receita,
            cd_natureza_receita := cd_natureza_receita,
            ds_natureza_receita := ds_natureza_receita,
            cd_especie_receita := cd_especie_receita,
            ds_especie_receita := ds_especie_receita,
            cd_cnae_doador := cd_cnae_doador,
            ds_cnae_doador := ds_cnae_doador,
            nr_cpf_cnpj_doador := nr_cpf_cnpj_doador,
            nm_doador := nm_doador,
            nm_doador_rfb := nm_doador_rfb,
            cd_esfera_partidaria_doador := cd_esfera_partidaria_doador,
            ds_esfera_partidaria_doador := ds_esfera_partidaria_doador,
            sg_uf_doador := sg_uf_doador,
            cd_municipio_doador := cd_municipio_doador,
            nm_municipio_doador := nm_municipio_doador,
            sq_candidato_doador := sq_candidato_doador,
            nr_candidato_doador := nr_candidato_doador,
            cd_cargo_candidato_doador := cd_cargo_candidato_doador,
            ds_cargo_candidato_doador := ds_cargo_candidato_doador,
            nr_partido_doador := nr_partido_doador,
            sg_partido_doador := sg_partido_doador,
            nm_partido_doador := nm_partido_doador,
            nr_recibo_doacao := nr_recibo_doacao,
            nr_documento_doacao := nr_documento_doacao,
            sq_receita := sq_receita,
            dt_receita := dt_receita,
            ds_receita := ds_receita,
            vr_receita := vr_receita,
            ds_natureza_recurso_estimavel := ds_natureza_recurso_estimavel,
            ds_genero := ds_genero,
            ds_cor_raca := ds_cor_raca
        )) as linha_original,
        case
            when trim(nr_cnpj_prestador_conta) = '-4' then 'sentinela_menos4'
            when nullif(trim(nr_cnpj_prestador_conta), '') is null then 'nao_informado'
            when regexp_matches(trim(nr_cnpj_prestador_conta), '^-[0-9]+$') then 'codigo_negativo'
        end::varchar as nr_cnpj_prestador_conta_ausencia,
        case
            when trim(nr_cpf_candidato) = '-4' then 'sentinela_menos4'
            when nullif(trim(nr_cpf_candidato), '') is null then 'nao_informado'
            when regexp_matches(trim(nr_cpf_candidato), '^-[0-9]+$') then 'codigo_negativo'
        end::varchar as nr_cpf_candidato_ausencia,
        case
            when trim(nr_cpf_vice_candidato) = '-4' then 'sentinela_menos4'
            when nullif(trim(nr_cpf_vice_candidato), '') is null then 'nao_informado'
            when regexp_matches(trim(nr_cpf_vice_candidato), '^-[0-9]+$') then 'codigo_negativo'
        end::varchar as nr_cpf_vice_candidato_ausencia,
        case
            when trim(nr_cpf_cnpj_doador) = '-4' then 'sentinela_menos4'
            when nullif(trim(nr_cpf_cnpj_doador), '') is null then 'nao_informado'
            when regexp_matches(trim(nr_cpf_cnpj_doador), '^-[0-9]+$') then 'codigo_negativo'
        end::varchar as nr_cpf_cnpj_doador_ausencia
    from {{ fonte_tse('receitas') }}
)

select
    *,
    dt_eleicao as data_eleicao,
    'tse:' || cd_eleicao || ':' || sq_candidato as candidatura_id,
    tp_prestacao_contas as tipo_prestacao,
    dt_prestacao_contas as data_prestacao,
    {{ documento_valido('nr_cnpj_prestador_conta') }} as nr_cnpj_prestador_conta_valido,
    {{ documento_valido('nr_cpf_candidato') }} as nr_cpf_candidato_valido,
    {{ documento_valido('nr_cpf_vice_candidato') }} as nr_cpf_vice_candidato_valido,
    {{ documento_valido('nr_cpf_cnpj_doador') }} as nr_cpf_cnpj_doador_valido,
    nr_cpf_candidato as cpf_candidato,
    nr_cpf_candidato_ausencia as cpf_candidato_ausencia,
    {{ documento_valido('nr_cpf_candidato') }} as cpf_candidato_valido
from tipado
where year(dt_eleicao) in (2018, 2020, 2022, 2024)
