-- depends_on: {{ source('raw_tse', 'pagamentos') }}
-- Camada privada: linha_original conserva todas as colunas fonte antes dos casts.
with tipado as (
    select
        {{ data_br('dt_geracao') }} as dt_geracao,
        hh_geracao::varchar as hh_geracao,
        nullif({{ texto('aa_eleicao') }}, '-4')::varchar as aa_eleicao,
        nullif({{ texto('cd_tipo_eleicao') }}, '-4')::varchar as cd_tipo_eleicao,
        nm_tipo_eleicao::varchar as nm_tipo_eleicao,
        nullif({{ texto('cd_eleicao') }}, '-4')::varchar as cd_eleicao,
        ds_eleicao::varchar as ds_eleicao,
        {{ data_br('dt_eleicao') }} as dt_eleicao,
        st_turno::varchar as st_turno,
        tp_prestacao_contas::varchar as tp_prestacao_contas,
        {{ data_br('dt_prestacao_contas') }} as dt_prestacao_contas,
        nullif({{ texto('sq_prestador_contas') }}, '-4')::varchar as sq_prestador_contas,
        sg_uf::varchar as sg_uf,
        ds_tipo_documento::varchar as ds_tipo_documento,
        nullif({{ texto('nr_documento') }}, '-4')::varchar as nr_documento,
        nullif({{ texto('cd_fonte_despesa') }}, '-4')::varchar as cd_fonte_despesa,
        ds_fonte_despesa::varchar as ds_fonte_despesa,
        nullif({{ texto('cd_origem_despesa') }}, '-4')::varchar as cd_origem_despesa,
        ds_origem_despesa::varchar as ds_origem_despesa,
        nullif({{ texto('cd_natureza_despesa') }}, '-4')::varchar as cd_natureza_despesa,
        ds_natureza_despesa::varchar as ds_natureza_despesa,
        nullif({{ texto('cd_especie_recurso') }}, '-4')::varchar as cd_especie_recurso,
        ds_especie_recurso::varchar as ds_especie_recurso,
        nullif({{ texto('sq_despesa') }}, '-4')::varchar as sq_despesa,
        nullif({{ texto('sq_parcelamento_despesa') }}, '-4')::varchar as sq_parcelamento_despesa,
        {{ data_br('dt_pagto_despesa') }} as dt_pagto_despesa,
        ds_despesa::varchar as ds_despesa,
        {{ numero_br('vr_pagto_despesa') }} as vr_pagto_despesa,
        _coleta_id,
        _competencia,
        _competencia_data,
        _linha,
        _arquivo_original,
        _carregado_em,
        ano_arquivo,
        versao_id,
        layout_id,
        to_json(struct_pack(
            dt_geracao := dt_geracao,
            hh_geracao := hh_geracao,
            aa_eleicao := aa_eleicao,
            cd_tipo_eleicao := cd_tipo_eleicao,
            nm_tipo_eleicao := nm_tipo_eleicao,
            cd_eleicao := cd_eleicao,
            ds_eleicao := ds_eleicao,
            dt_eleicao := dt_eleicao,
            st_turno := st_turno,
            tp_prestacao_contas := tp_prestacao_contas,
            dt_prestacao_contas := dt_prestacao_contas,
            sq_prestador_contas := sq_prestador_contas,
            sg_uf := sg_uf,
            ds_tipo_documento := ds_tipo_documento,
            nr_documento := nr_documento,
            cd_fonte_despesa := cd_fonte_despesa,
            ds_fonte_despesa := ds_fonte_despesa,
            cd_origem_despesa := cd_origem_despesa,
            ds_origem_despesa := ds_origem_despesa,
            cd_natureza_despesa := cd_natureza_despesa,
            ds_natureza_despesa := ds_natureza_despesa,
            cd_especie_recurso := cd_especie_recurso,
            ds_especie_recurso := ds_especie_recurso,
            sq_despesa := sq_despesa,
            sq_parcelamento_despesa := sq_parcelamento_despesa,
            dt_pagto_despesa := dt_pagto_despesa,
            ds_despesa := ds_despesa,
            vr_pagto_despesa := vr_pagto_despesa
        )) as linha_original
    from {{ fonte_tse('pagamentos') }}
)

select
    *,
    dt_eleicao as data_eleicao,
    tp_prestacao_contas as tipo_prestacao,
    dt_prestacao_contas as data_prestacao
from tipado
where year(dt_eleicao) in (2018, 2020, 2022, 2024)
