-- depends_on: {{ source('raw_tse', 'candidaturas') }}
-- Camada privada: linha_original conserva todas as colunas fonte antes dos casts.
with tipado as (
    select
        {{ data_br('dt_geracao') }} as dt_geracao,
        hh_geracao::varchar as hh_geracao,
        nullif({{ texto('ano_eleicao') }}, '-4')::varchar as ano_eleicao,
        nullif({{ texto('cd_tipo_eleicao') }}, '-4')::varchar as cd_tipo_eleicao,
        nm_tipo_eleicao::varchar as nm_tipo_eleicao,
        nullif({{ texto('nr_turno') }}, '-4')::varchar as nr_turno,
        nullif({{ texto('cd_eleicao') }}, '-4')::varchar as cd_eleicao,
        ds_eleicao::varchar as ds_eleicao,
        {{ data_br('dt_eleicao') }} as dt_eleicao,
        tp_abrangencia::varchar as tp_abrangencia,
        sg_uf::varchar as sg_uf,
        sg_ue::varchar as sg_ue,
        nm_ue::varchar as nm_ue,
        nullif({{ texto('cd_cargo') }}, '-4')::varchar as cd_cargo,
        ds_cargo::varchar as ds_cargo,
        nullif({{ texto('sq_candidato') }}, '-4')::varchar as sq_candidato,
        nullif({{ texto('nr_candidato') }}, '-4')::varchar as nr_candidato,
        nm_candidato::varchar as nm_candidato,
        nm_urna_candidato::varchar as nm_urna_candidato,
        nm_social_candidato::varchar as nm_social_candidato,
        {{ documento_fonte("nullif(trim(nr_cpf_candidato), '-4')") }} as nr_cpf_candidato,
        ds_email::varchar as ds_email,
        nullif({{ texto('cd_situacao_candidatura') }}, '-4')::varchar as cd_situacao_candidatura,
        ds_situacao_candidatura::varchar as ds_situacao_candidatura,
        tp_agremiacao::varchar as tp_agremiacao,
        nullif({{ texto('nr_partido') }}, '-4')::varchar as nr_partido,
        sg_partido::varchar as sg_partido,
        nm_partido::varchar as nm_partido,
        nullif({{ texto('nr_federacao') }}, '-4')::varchar as nr_federacao,
        nm_federacao::varchar as nm_federacao,
        sg_federacao::varchar as sg_federacao,
        ds_composicao_federacao::varchar as ds_composicao_federacao,
        nullif({{ texto('sq_coligacao') }}, '-4')::varchar as sq_coligacao,
        nm_coligacao::varchar as nm_coligacao,
        ds_composicao_coligacao::varchar as ds_composicao_coligacao,
        sg_uf_nascimento::varchar as sg_uf_nascimento,
        {{ data_br('dt_nascimento') }} as dt_nascimento,
        nullif({{ texto('nr_titulo_eleitoral_candidato') }}, '-4')::varchar
            as nr_titulo_eleitoral_candidato,
        nullif({{ texto('cd_genero') }}, '-4')::varchar as cd_genero,
        ds_genero::varchar as ds_genero,
        nullif({{ texto('cd_grau_instrucao') }}, '-4')::varchar as cd_grau_instrucao,
        ds_grau_instrucao::varchar as ds_grau_instrucao,
        nullif({{ texto('cd_estado_civil') }}, '-4')::varchar as cd_estado_civil,
        ds_estado_civil::varchar as ds_estado_civil,
        nullif({{ texto('cd_cor_raca') }}, '-4')::varchar as cd_cor_raca,
        ds_cor_raca::varchar as ds_cor_raca,
        nullif({{ texto('cd_ocupacao') }}, '-4')::varchar as cd_ocupacao,
        ds_ocupacao::varchar as ds_ocupacao,
        nullif({{ texto('cd_sit_tot_turno') }}, '-4')::varchar as cd_sit_tot_turno,
        ds_sit_tot_turno::varchar as ds_sit_tot_turno,
        _coleta_id,
        _competencia,
        _competencia_data,
        _linha,
        _arquivo_original,
        _carregado_em,
        ano_arquivo,
        versao_id,
        layout_id,
        to_json(struct_pack(
            dt_geracao := dt_geracao,
            hh_geracao := hh_geracao,
            ano_eleicao := ano_eleicao,
            cd_tipo_eleicao := cd_tipo_eleicao,
            nm_tipo_eleicao := nm_tipo_eleicao,
            nr_turno := nr_turno,
            cd_eleicao := cd_eleicao,
            ds_eleicao := ds_eleicao,
            dt_eleicao := dt_eleicao,
            tp_abrangencia := tp_abrangencia,
            sg_uf := sg_uf,
            sg_ue := sg_ue,
            nm_ue := nm_ue,
            cd_cargo := cd_cargo,
            ds_cargo := ds_cargo,
            sq_candidato := sq_candidato,
            nr_candidato := nr_candidato,
            nm_candidato := nm_candidato,
            nm_urna_candidato := nm_urna_candidato,
            nm_social_candidato := nm_social_candidato,
            nr_cpf_candidato := nr_cpf_candidato,
            ds_email := ds_email,
            cd_situacao_candidatura := cd_situacao_candidatura,
            ds_situacao_candidatura := ds_situacao_candidatura,
            tp_agremiacao := tp_agremiacao,
            nr_partido := nr_partido,
            sg_partido := sg_partido,
            nm_partido := nm_partido,
            nr_federacao := nr_federacao,
            nm_federacao := nm_federacao,
            sg_federacao := sg_federacao,
            ds_composicao_federacao := ds_composicao_federacao,
            sq_coligacao := sq_coligacao,
            nm_coligacao := nm_coligacao,
            ds_composicao_coligacao := ds_composicao_coligacao,
            sg_uf_nascimento := sg_uf_nascimento,
            dt_nascimento := dt_nascimento,
            nr_titulo_eleitoral_candidato := nr_titulo_eleitoral_candidato,
            cd_genero := cd_genero,
            ds_genero := ds_genero,
            cd_grau_instrucao := cd_grau_instrucao,
            ds_grau_instrucao := ds_grau_instrucao,
            cd_estado_civil := cd_estado_civil,
            ds_estado_civil := ds_estado_civil,
            cd_cor_raca := cd_cor_raca,
            ds_cor_raca := ds_cor_raca,
            cd_ocupacao := cd_ocupacao,
            ds_ocupacao := ds_ocupacao,
            cd_sit_tot_turno := cd_sit_tot_turno,
            ds_sit_tot_turno := ds_sit_tot_turno
        )) as linha_original,
        case
            when trim(nr_cpf_candidato) = '-4' then 'sentinela_menos4'
            when nullif(trim(nr_cpf_candidato), '') is null then 'nao_informado'
            when regexp_matches(trim(nr_cpf_candidato), '^-[0-9]+$') then 'codigo_negativo'
        end::varchar as nr_cpf_candidato_ausencia
    from {{ fonte_tse('candidaturas') }}
)

select
    *,
    dt_eleicao as data_eleicao,
    'tse:' || cd_eleicao || ':' || sq_candidato as candidatura_id,
    {{ documento_valido('nr_cpf_candidato') }} as nr_cpf_candidato_valido,
    nr_cpf_candidato as cpf_candidato,
    nr_cpf_candidato_ausencia as cpf_candidato_ausencia,
    {{ documento_valido('nr_cpf_candidato') }} as cpf_candidato_valido
from tipado
where year(dt_eleicao) in (2018, 2020, 2022, 2024)
