-- Contratos do Poder Executivo federal (Portal da Transparência, 2013 em diante, e PNCP, 2021 em
-- diante, pareados). CPF mascarado.
select
    contrato_id,
    id_cgu,
    id_pncp,
    fonte,
    contrato_numero,
    ug_codigo,
    {{ mascarar_cpfs_em_texto('ug_nome') }} as ug_nome,
    orgao_nome,
    orgao_superior_nome,
    {{ mascarar_cpfs_em_texto('objeto') }} as objeto,
    tipo_contrato,
    modalidade,
    data_assinatura,
    data_inicio_vigencia,
    data_fim_vigencia,
    {{ documento_publico('fornecedor_documento') }} as fornecedor_documento,
    fornecedor_tipo_documento,
    fornecedor_documento_valido,
    fornecedor_cnpj_raiz,
    {{ mascarar_cpfs_em_texto('fornecedor_nome') }} as fornecedor_nome,
    valor_inicial,
    valor_final,
    compra_pncp_id,
    licitacao_numero,
    emenda_parlamentar,
    _coleta_id
from {{ ref('int_contratos_federais') }}
