-- Documentos de despesa (empenho, liquidação, pagamento) de emendas, um arquivo por ano.
select
    _coleta_id,
    _competencia,
    if(regexp_matches(coalesce({{ texto('codigo_da_emenda') }}, ''), '^[0-9]+$'), {{ texto('codigo_da_emenda') }}, null)
        as emenda_codigo,
    try_cast({{ texto('ano_da_emenda') }} as integer) as ano_emenda,
    nullif({{ texto('codigo_do_autor_da_emenda') }}, 'S/I') as autor_codigo,
    nullif({{ texto('nome_do_autor_da_emenda') }}, 'Sem informação') as autor_nome,
    nullif({{ texto('numero_da_emenda') }}, 'S/I') as numero_emenda,
    {{ texto('tipo_de_emenda') }} as tipo_emenda,
    {{ numero_br('valor_empenhado') }} as valor_empenhado,
    {{ numero_br('valor_pago') }} as valor_pago,
    {{ data_br('data_documento') }} as data_documento,
    {{ texto('codigo_documento') }} as documento_codigo,
    {{ texto('fase_da_despesa') }} as fase_despesa,
    {{ texto('localidade_de_aplicacao_do_recurso') }} as localidade,
    {{ texto('uf_de_aplicacao_do_recurso') }} as uf_sigla,
    if(regexp_matches(coalesce({{ texto('codigo_ibge_do_municipio_de_aplicacao_do_recurso') }}, ''), '^[0-9]{7}$'),
        {{ texto('codigo_ibge_do_municipio_de_aplicacao_do_recurso') }}, null) as municipio_id,
    {{ documento_fonte('codigo_favorecido') }} as favorecido_documento,
    {{ tipo_documento_fonte('codigo_favorecido') }} as favorecido_tipo_documento,
    {{ texto('favorecido') }} as favorecido_nome,
    {{ texto('tipo_favorecido') }} as tipo_favorecido,
    {{ texto('uf_favorecido') }} as favorecido_uf,
    {{ texto('municipio_favorecido') }} as favorecido_municipio,
    {{ texto('codigo_ug') }} as ug_codigo,
    {{ texto('ug') }} as ug_nome,
    {{ texto('codigo_orgao_siafi') }} as orgao_codigo,
    {{ texto('orgao') }} as orgao_nome,
    {{ texto('codigo_orgao_superior_siafi') }} as orgao_superior_codigo,
    {{ texto('orgao_superior') }} as orgao_superior_nome,
    {{ texto('grupo_despesa') }} as grupo_despesa,
    {{ texto('elemento_despesa') }} as elemento_despesa,
    {{ texto('modalidade_aplicacao_despesa') }} as modalidade_aplicacao,
    {{ texto('funcao') }} as funcao,
    {{ texto('subfuncao') }} as subfuncao,
    {{ texto('programa') }} as programa,
    {{ texto('acao') }} as acao,
    {{ texto('possui_convenio') }} = 'SIM' as possui_convenio,
    md5(to_json(struct_pack(*columns(* exclude (
        _coleta_id, _competencia, _competencia_data, _linha, _arquivo_original, _carregado_em
    ))))) as hash_linha
from {{ source('raw_cgu', 'emendas_documentos') }}
