-- Estabelecimentos (matriz e filiais) do recorte da Receita, em todas as competências coletadas.
-- Endereço e contato ficam no lago privado; os marts não os publicam.
select
    _coleta_id,
    _competencia as competencia,
    {{ texto('cnpj_basico') }} as cnpj_raiz,
    concat({{ texto('cnpj_basico') }}, {{ texto('cnpj_ordem') }}, {{ texto('cnpj_dv') }}) as cnpj,
    {{ texto('identificador_matriz_filial') }} = '1' as matriz,
    {{ texto('nome_fantasia') }} as nome_fantasia,
    {{ texto('situacao_cadastral') }} as situacao_codigo,
    {{ data_rfb('data_situacao_cadastral') }} as data_situacao,
    {{ texto('motivo_situacao_cadastral') }} as motivo_codigo,
    {{ texto('nome_cidade_exterior') }} as cidade_exterior,
    {{ texto('pais') }} as pais_codigo,
    {{ data_rfb('data_inicio_atividade') }} as data_inicio_atividade,
    {{ texto('cnae_fiscal_principal') }} as cnae_principal,
    {{ texto('cnae_fiscal_secundaria') }} as cnaes_secundarios,
    {{ texto('tipo_logradouro') }} as tipo_logradouro,
    {{ texto('logradouro') }} as logradouro,
    {{ texto('numero') }} as numero,
    {{ texto('complemento') }} as complemento,
    {{ texto('bairro') }} as bairro,
    {{ texto('cep') }} as cep,
    {{ texto('uf') }} as uf_sigla,
    {{ texto('municipio') }} as municipio_rfb_codigo,
    {{ texto('ddd_1') }} as ddd_1,
    {{ texto('telefone_1') }} as telefone_1,
    {{ texto('ddd_2') }} as ddd_2,
    {{ texto('telefone_2') }} as telefone_2,
    {{ texto('ddd_fax') }} as ddd_fax,
    {{ texto('fax') }} as fax,
    {{ texto('correio_eletronico') }} as correio_eletronico,
    {{ texto('situacao_especial') }} as situacao_especial,
    {{ data_rfb('data_situacao_especial') }} as data_situacao_especial
from {{ source('raw_rfb', 'estabelecimentos') }}
